version: '3.4'

volumes:
  saves:

services:
  example:
    container_name: example
    volumes:
      - ./data/saves:/service/data/saves
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        run_cmd: "./svdistic svdpp train -n_epochs 10 -report_freq 1 -fname dummy.data -n_user 4 -n_product 3 -n_example 11 -lr 0.007 -reg_bias 0.005 -reg_weight 0.015 -lr_decay 0.9"
        n_latent: 400
    tty: true

  svd_benchmark:
    container_name: svd_benchmark
    volumes:
      - ./data/saves:/service/data/saves
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        run_cmd: "./svdistic svd train -n_epochs 10 -report_freq 1 -fname base.data -n_user 458294 -n_product 17771 -n_example 94362233 -lr 0.007 -reg_bias 0.005 -reg_weight 0.015 -lr_decay 0.9"
        n_latent: 100
    tty: true

  svdpp_benchmark:
    container_name: svdpp_benchmark
    volumes:
      - ./data/saves:/service/data/saves
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        run_cmd: "./svdistic svdpp train -n_epochs 10 -report_freq 1 -fname base.data -n_user 458294 -n_product 17771 -n_example 94362233 -lr 0.007 -reg_bias 0.005 -reg_weight 0.015 -lr_decay 0.9"
        n_latent: 100
    tty: true

